version: "3.8"

services:
  app:
    build:
      context: "."
      dockerfile: Dockerfile.node
    container_name: node
    command: >
      sh -c "npm run run:migration && npm start"
    ports:
      - "3000:3000"
    volumes:
      - ./node:/app
    depends_on:
      - db

  web:
    build:
      context: "."
      dockerfile: Dockerfile.php
    container_name: php-apache
    volumes:
      - ./php:/var/www/html
    ports:
      - "8080:80"
    depends_on:
      - db

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: "12345"
    ports:
      - "8081:80"
    depends_on:
      - db

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "12345"
      MYSQL_DATABASE: "project_deanta"
    volumes:
      - db_data:/var/lib/mysql
      - ./php/db:/docker-entrypoint-initdb.d
    command: ["--init-file", "/docker-entrypoint-initdb.d/script.sql"]
    ports:
      - "3306:3306"

volumes:
  db_data:
